apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-todo
  template:
    metadata:
      labels:
        app: go-todo # ✅ This is the crucial pod label
    spec:
      containers:
          
        - name: go-todoconsumer
          image: andrews326/go-todo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: todo-config
                  key: DB_NAME
            - name: JWT_SECRET
              value: G9s!zX7$eA2@tKp
---
apiVersion: v1
kind: Service
metadata:
  name: go-todo
spec:
  selector:
    app: go-todo # ✅ Matches pod label
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30001
  type: NodePort
